### ISSUE TITLE
Infinite wait example

### ISSUE THREAD

**Issue by gromenauer** [1271/hoper#2]
This waits for ever:
~~~
hoper https://read.lhtranslation.com/manga-jui-san-no-oshigoto-in-isekai.html -lj
~~~

**Comment by 1271** [comment]
Oh...
if( $('#signin_output').text() == '...' ){ window.location.href='http://lhtranslation.net/manga-jui-san-no-oshigoto-in-isekai.html'; }
Thanks )
Fixed. Check version 1.3 (`-F` argument)

**Comment by 1271** [comment]
P.S. also now `hoper` will not correctly follow links that use variables (js).

I’ll probably never use js-eval for this project

**Comment by 1271** [comment]
I close this issue
